- menu_name: "Extras"


- name: "About"
  url: "/info/"
  title: "Learn more about Kimberly"

- name: "Contact"
  url: "/contact/"
  title: "Contact Kimberly"


- name: "This is Metis"
  url: "https://www.thisismetis.com"
  title: "Learn more about Metis"

#
#- name: "RSS"
#  url: "/feed.xml"
#  title: "Subscribe to RSS Feed"
#
#- name: "Atom"
#  url: "/atom.xml"
#  title: "Subscribe to Atom Feed"
#
#- name: "sitemap.xml"
#  url: "/sitemap.xml"
#  title: "Sitemap for Google Webmaster Tools"
