- menu_name: "Extras"

- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "Metis"
  url: "https://www.thisismetis.com"
  title: "This is Metis"

#
#- name: "RSS"
#  url: "/feed.xml"
#  title: "Subscribe to RSS Feed"
#
#- name: "Atom"
#  url: "/atom.xml"
#  title: "Subscribe to Atom Feed"
#
#- name: "sitemap.xml"
#  url: "/sitemap.xml"
#  title: "Sitemap for Google Webmaster Tools"
