- menu_name: "Extras"

- name: "About Metis"
  url: "https://www.thisismetis.com"
  title: "Learn more about Metis"

- name: "About Kimberly"
  url: "/info/"
  title: "Learn more about Kimberly"

- name: "Contact"
  url: "/contact/"
  title: "Contact"


#
#- name: "RSS"
#  url: "/feed.xml"
#  title: "Subscribe to RSS Feed"
#
#- name: "Atom"
#  url: "/atom.xml"
#  title: "Subscribe to Atom Feed"
#
#- name: "sitemap.xml"
#  url: "/sitemap.xml"
#  title: "Sitemap for Google Webmaster Tools"
